#include "TableSync.h"

//WorkerID为0表示同步工作线程
//WorkerID为-1表示结束
TTaskMethod g_TaskMethod[] =
{
	{1,TMT_GN_INIT,TMT_TABLE,&(CServiceConfigField::m_Describe),"CServiceConfigField","ServiceConfig","ConfigName,Index1,Index2",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CCurrencyField::m_Describe),"CCurrencyField","Currency","Currency,SettlementGroup",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CMarketDataField::m_Describe),"CMarketDataField","MarketData","ExchangeID,InstrumentID",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CInstrumentField::m_Describe),"CInstrumentField","Instrument","ExchangeID,InstrumentID",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CCurrentTimeField::m_Describe),"CCurrentTimeField","CurrentTime","SystemID",{0},{0},{0},{0}},		
	{5,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{6,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{7,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{8,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{9,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{10,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{11,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{12,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{13,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{14,TMT_GN_INIT,TMT_TABLE,&(CMemberField::m_Describe),"CMemberField","Member","MemberID",{0},{0},{0},{0}},
	{1,TMT_GN_INIT,TMT_TABLE,&(CUserSessionField::m_Describe),"CUserSessionField","UserSession","Token",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CLastKLineField::m_Describe),"CLastKLineField","LastKLine","ExchangeID,InstrumentID,Bar",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CCFDRateField::m_Describe),"CCFDRateField","CFDRate","MemberID,InstrumentID,TriggerOrderType",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CTradingRightField::m_Describe),"CTradingRightField","TradingRight","MemberID,InstrumentID,Direction",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CMarginRateField::m_Describe),"CMarginRateField","MarginRate","MemberID,InstrumentID",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CFeeField::m_Describe),"CFeeField","Fee","MemberID,InstrumentID,MatchRole",{0},{0},{0},{0}},		
	{1,TMT_GN_INIT,TMT_TABLE,&(CLiquidityField::m_Describe),"CLiquidityField","Liquidity","LiquidityGrade,LiquidityGroup",{0},{0},{0},{0}},		
	{5,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{6,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{7,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{8,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{9,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{10,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{11,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{12,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{13,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{14,TMT_GN_INIT,TMT_TABLE,&(CAccountField::m_Describe),"CAccountField","Account","AccountID,Currency,SettlementGroup",{0},{0},{0},{0}},
	{15,TMT_GN_INIT,TMT_TABLE,&(CMemberPositionField::m_Describe),"CMemberPositionField","MemberPosition","MemberID,AccountID,ExchangeID,InstrumentID",{0},{0},{0},{0}},		
	{15,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{16,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{17,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{18,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{19,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{20,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{21,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{22,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{23,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{24,TMT_GN_INIT,TMT_TABLE,&(CPositionField::m_Describe),"CPositionField","Position","PositionID",{0},{0},{0},{0}},
	{25,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{26,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{27,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{28,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{29,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{30,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{31,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{32,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{33,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{34,TMT_GN_INIT,TMT_TABLE,&(COrderField::m_Describe),"COrderField","Order","OrderID",{0},{0},{0},{0}},
	{2,TMT_GN_INIT,TMT_TABLE,&(CTriggerOrderField::m_Describe),"CTriggerOrderField","TriggerOrder","OrderID",{0},{0},{0},{0}},		
	{15,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{16,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{17,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{18,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{19,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{20,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{21,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{22,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{23,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{24,TMT_GN_INIT,TMT_TABLE,&(CPositionOrderField::m_Describe),"CPositionOrderField","PositionOrder","OrderID",{0},{0},{0},{0}},
	{100,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{101,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{102,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{103,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{104,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{105,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{106,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{107,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{108,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{109,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder","OrderID",{0},{0},{0},{0}},
	{110,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{111,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{112,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{113,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{114,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{115,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{116,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{117,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{118,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{119,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade","TradeID,Direction",{0},{0},{0},{0}},
	{110,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{111,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{112,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{113,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{114,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{115,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{116,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{117,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{118,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{119,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition","PositionID",{0},{0},{0},{0}},
	{120,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{121,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{122,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{123,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{124,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{125,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{126,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{127,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{128,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{129,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail","AccountDetailID",{0},{0},{0},{0}},
	{130,TMT_GN_DOWN,TMT_TABLE,&(CKLineField::m_Describe),"CKLineField","KLine","ExchangeID,InstrumentID,Bar,InsertTime",{0},{0},{0},{0}},		
	{130,TMT_GN_DOWN,TMT_TABLE,&(CSettleDetailField::m_Describe),"CSettleDetailField","SettleDetail","ExchangeID,InstrumentID,SettleDetailID",{0},{0},{0},{0}},		
	{130,TMT_GN_DOWN,TMT_TABLE,&(CFinishTriggerOrderField::m_Describe),"CFinishTriggerOrderField","FinishTriggerOrder","OrderID",{0},{0},{0},{0}},		
	{-1,TMT_GN_INIT,TMT_TABLE,NULL,"","","",{0},{0},{0},{0}}
};

//TSingleMethod g_SingleMethod[] =
//{
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//
//	
//	
//	{100,TMT_GN_DOWN,TMT_TABLE,&(CFinishOrderField::m_Describe),"CFinishOrderField","FinishOrder",true},		
//		
//
//
//
//	
//	
//	{110,TMT_GN_DOWN,TMT_TABLE,&(CTradeField::m_Describe),"CTradeField","Trade",true},		
//		
//
//
//
//	
//	
//	{110,TMT_GN_DOWN,TMT_TABLE,&(CFinishPositionField::m_Describe),"CFinishPositionField","FinishPosition",true},		
//		
//
//
//
//	
//	
//	{120,TMT_GN_DOWN,TMT_TABLE,&(CAccountDetailField::m_Describe),"CAccountDetailField","AccountDetail",true},		
//		
//
//
//
//	
//	
//	{130,TMT_GN_DOWN,TMT_TABLE,&(CKLineField::m_Describe),"CKLineField","KLine",true},		
//		
//
//
//
//	
//	
//	{130,TMT_GN_DOWN,TMT_TABLE,&(CSettleDetailField::m_Describe),"CSettleDetailField","SettleDetail",true},		
//		
//
//
//
//	
//	
//	{130,TMT_GN_DOWN,TMT_TABLE,&(CFinishTriggerOrderField::m_Describe),"CFinishTriggerOrderField","FinishTriggerOrder",true},		
//		
//
//
//
//	
//		
//
//
//
//	
//		
//
//
//	{-1,TMT_GN_INIT,TMT_TABLE,NULL,"","",true}
//};

TTinitTableInfo g_LoadTableInfo[] = 
{
	{"ServiceConfig",&CServiceConfigField::m_Describe},
	{"Currency",&CCurrencyField::m_Describe},
	{"MarketData",&CMarketDataField::m_Describe},
	{"Instrument",&CInstrumentField::m_Describe},
	{"CurrentTime",&CCurrentTimeField::m_Describe},
	{"Member",&CMemberField::m_Describe},
	{"UserSession",&CUserSessionField::m_Describe},
	{"CFDRate",&CCFDRateField::m_Describe},
	{"TradingRight",&CTradingRightField::m_Describe},
	{"MarginRate",&CMarginRateField::m_Describe},
	{"Fee",&CFeeField::m_Describe},
	{"Liquidity",&CLiquidityField::m_Describe},
	{"Account",&CAccountField::m_Describe},
	{"Position",&CPositionField::m_Describe},
	{"Order",&COrderField::m_Describe},
	{"TriggerOrder",&CTriggerOrderField::m_Describe},
	{NULL,NULL}				//一定要有这一行，表示结束
};

