/////////////////////////////////////////////////////////////////////////
///errorDefine.h
///定义了各种错误
/////////////////////////////////////////////////////////////////////////

#ifndef ERRORDEFINE_H
#define ERRORDEFINE_H

#include "CErrorEngine.h"

#define ERROR_NONE 0
#define ERROR_SystemNotReady 1
#define ERROR_RECORD_NOT_FOUND 2
#define ERROR_RECORD_EXIST 3
#define ERROR_INVALID_ACTION 4
#define ERROR_INVALID_VALUE 5
#define ERROR_InvalidStatus 6
#define ERROR_INVALID_SESSION 7
#define ERROR_INSTRUMENT_NOT_FOUND 8
#define ERROR_MEMBER_NOT_FOUND 9
#define ERROR_MARKETDATA_NOT_FOUND 11
#define ERROR_BAD_FIELD 12
#define ERROR_DUPLICATE_ACTION 14
#define ERROR_MARKET_ORDER_CAN_NOT_QUEUE 18
#define ERROR_GTD_ORDER_EXPIRED 20
#define ERROR_MV_ORDER_EXCEED_VOLUMN 21
#define ERROR_ORDER_EXIST 22
#define ERROR_ORDER_NOT_FOUND 24
#define ERROR_QUOTE_NOT_FOUND 25
#define ERROR_INVALID_INSTRUMENT_STATUS 26
#define ERROR_INVALID_INSTRUMENT_STATUS_SHIFT 27
#define ERROR_NOT_ENOUGH_VOLUME_TO_MODIFY 30
#define ERROR_NOT_ENOUGH_POSITION_TO_CLOSE 31
#define ERROR_POSITION_LIMIT_EXCEED 32
#define ERROR_AccountLessThanZeroAfterClose 33
#define ERROR_MEMBER_POSITION_LIMIT_EXCEED 34
#define ERROR_AccountNotFound 35
#define ERROR_INSUFFICIENT_MONEY 36
#define ERROR_INVALID_VOLUME 37
#define ERROR_VOLUME_NOT_ON_TICK 44
#define ERROR_PRICE_NOT_ON_TICK 48
#define ERROR_PriceOutOfUpperLimit 49
#define ERROR_PriceOutOfLowerLimit 50
#define ERROR_NO_TRADING_RIGHT 51
#define ERROR_CLOSE_ONLY 52
#define ERROR_USER_NOT_LOGIN 54
#define ERROR_ONLY_TRADE_MANAGER_CAN_DO_THIS 56
#define ERROR_USER_MISMATCH 58
#define ERROR_USER_RELOGIN 59
#define ERROR_INVALID_USER_OR_PASSWORD 60
#define ERROR_USER_NOT_ACTIVE 62
#define ERROR_INVALID_LOGIN_IPADDRESS 65
#define ERROR_CAN_NOT_OPERATE_DERIVED_ORDER 71
#define ERROR_ORDER_HAD_SUSPENDED 76
#define ERROR_ORDER_HAD_ACTIVED 77
#define ERROR_GTD_ORDER_DATE_MISSED 78
#define ERROR_UnSupportOrderType 79
#define ERROR_USER_NO_PERMISSION 80
#define ERROR_USER_NOT_FOUND 88
#define ERROR_CanNotActionForOtherUser 99
#define ERROR_NotEnoughMargin 100
#define ERROR_COMBINATION_ON_SINGLE_INSTRUMENT 118
#define ERROR_OTC_TYPE_ERROR 139
#define ERROR_NOT_ENOUGH_LEVERAGE 172
#define ERROR_PRICE_MUST_GREATER_THAN_ZERO 175
#define ERROR_INVALID_APIKEY 176
#define ERROR_APIKEY_EXPIRED 177
#define ERROR_APIKEY_LIMIT_EXCEED 178
#define ERROR_KEY_IS_NULL 179
#define ERROR_CAN_NOT_FIND_MARGIN_RATE 180
#define ERROR_DUPLICATE_APIKEY 181
#define ERROR_NO_LIMITPRICE 182
#define ERROR_EXCEED_MAX_QUERY_COUNT_PER_SECOND 183
#define ERROR_ORDER_LIMIT_EXCEED 184
#define ERROR_NOT_ENOUGH_OPENORDERS 185
#define ERROR_SESSION_NOT_FOUND 186
#define ERROR_PRICE_OUT_OF_ASKPRICE1 187
#define ERROR_PRICE_OUT_OF_BIDPRICE1 188
#define ERROR_POSITION_EXIST 189
#define ERROR_UnderlyingPriceError 190
#define ERROR_RecordAnalysisError 191
#define ERROR_DuplicateRecord 192
#define ERROR_OutOfMaxVolume 193
#define ERROR_LessThanMinVolume 194
#define ERROR_PositionLessThanMinVolume 195
#define ERROR_TRADE_FORBIDDEN 196
#define ERROR_CAN_NOT_FIND_FEE 197
#define ERROR_POSITION_COUNT_LIMIT_EXCEED 198
#define ERROR_LEVERAGE_TOO_HIGH 199
#define ERROR_POSITION_UNDER_DEFICIT 200
#define ERROR_CAN_NOT_CHANGE_POSTYPE 201

///定义所有的错误
///@param	pEngine	要定义错误的错误引擎
void defineErrors(CErrorEngine *pEngine);

#endif
