#!/bin/bash

workdir=$(cd $(dirname $0); pwd)
cd $workdir

cntexpr=`wc -l list.hosts | awk '{print $1}'`
cntall=`expr $cntexpr`

i=0
while [ $i -lt $cntall ]
do
	i=`expr $i + 1 `
	read hosts
	echo "("$i")" $hosts
	ssh -n $hosts 'cd deploy;chmod u+x chkini.sh;./chkini.sh'	
done < list.hosts
