#!/bin/bash

workdir=$(cd $(dirname $0); pwd)
cd $workdir

cntexpr=`wc -l list.hosts | awk '{print $1}'`
cntall=`expr $cntexpr`

i=0
while [ $i -lt $cntall ]
do
	i=`expr $i + 1 `
	read hosts
	name=`ssh -n $hosts hostname`
	echo "("$i")" $hosts [$name]
	echo scp -r $hosts:./deploy/list.run ./$i.list.run
	scp -r $hosts:./deploy/list.run ./$i.list.run
done < list.hosts
